### ISSUE TITLE
Eraser messes up everything

### ISSUE THREAD

**Issue by merobal** [akoidan/spainter#2]
In the latest Chrome, after I click on the eraser (even if I don't use that) I can't use the Line, the Rectangle and the Eclipse, and also the Select removes the selected area after I click outside.

Steps to reproduce:
- Draw something
- Click on Eraser
- Try to use the functions listed above.

**Comment by akoidan** [comment]
Thanks for reporting the issue, it's fixed in [0.1.3](https://www.npmjs.com/package/spainter/v/0.1.3)
