### ISSUE TITLE
How do I add an image in the background by default?

### ISSUE THREAD

**Issue by aahedi** [akoidan/spainter#4]
I really appreciate your cool project,
I using client side with embed `<script src="https://cdn.jsdelivr.net/npm/spainter@1.0.0/index.js"></script>`
How do I adjust the canvas size?
How do I add an image in the background by default?
How do I save my canvas? For example like save in localstorage and load next time?

**Comment by akoidan** [comment]
1. Specify the latest versions on both js and css: `<script src="https://cdn.jsdelivr.net/npm/spainter@1.2.10/index.js"></script>`

> How do I adjust the canvas size?
- Why do you need it? it already fits the remaining screen. Make elements around the canvas smaller it takes the bigger portion of the screen. Make them large it takes the rest. 
- Use css selectors: `#containerPainter canvas: width; height`
- Use js: document.querySelector('#containerPainter  canvas') and manipulate the width and height manually
> How do I add an image in the background by default?
 - Use css     `background-image:` property on `#containerPainter  canvas`
> How do I save my canvas. 
 - get canvas element from js `document.querySelector('#containerPainter  canvas')` and do w/e you want with it. E.g.  `canvas.toDataURL();` and save to localStorage.

**Comment by aahedi** [comment]
Yes that's a great idea.
when I use `canvas.toDataURL` unfortunately the `background-image` is not included in the result image.
I use this for mobile, How do to zooming the canvas using like pinch zoom and dragging zooming canvas with pinch?

**Comment by akoidan** [comment]
Once you obtain the canvas you can work with it like with any other canvas element. You can easily google that.

**Comment by akoidan** [comment]
I'm closing this issue due 10 days of inactivity
