### ISSUE TITLE
Initialize Painter with different values

### ISSUE THREAD

**Issue by giladsagiv** [akoidan/spainter#5]
Hi,
Great library ! thanks for that
I was wondering if there is a way to initialize the Painter with different values (color,fill,zoom,width,opacity ,etc.) then the ones hard coded in it. 
The reason i need it its because i want to load previouse setting the user has selected (i'm listnening to changes in severl inputs and save it localy as user prefrences).
I manage to do it with  : 
```
spaint.instruments.color.ctxSetter(preset.paintColorFill);
$('.paintColor input[type=color]').val(preset.paintColorFill);
```
Where **preset** is my local storage object , and in the end 
`spaint.helper.setCursor(spaint.helper.buildCursor(spaint.ctx.strokeStyle, '', spaint.ctx.lineWidth))`

But i think it is not the way this should be done.
Any thoughts?
Thanks again

**Comment by akoidan** [comment]
Yep, unfortunately this feature in unavailable out of the box. SO your method is correct. 

You can also create a pull request so you don't need to access global properties like this 
```
spaint.instruments.color.ctxSetter(preset.paintColorFill);
```
For the inputs instead of this 
```
$('.paintColor input[type=color]').val(preset.paintColorFill);
```
you can access dom with `spaint.instruments.color.value` which is equal `$('.paintColor input[type=color]')`. So
```
spaint.instruments.color.value.value = '#ff0000'
```

**Comment by akoidan** [comment]
This should be a lot easier when I release the 2nd version, which is based on TS and OOP. But I don't have time right now to finish this work. The work is in the [ts](https://github.com/akoidan/spainter/tree/ts) branch and it's like 30 hours of work left.

**Comment by giladsagiv** [comment]
Thanks for the response. 
i'll make the chnages in my code to reflect your suggestions.
I'm closing the issue.
