### ISSUE TITLE
Saving drawn content as png to server

### ISSUE THREAD

**Issue by rdimaunahan** [akoidan/spainter#7]
Is there a way to grab the content that was drawn in the drawing area and then save it as png in a server folder?

**Comment by akoidan** [comment]
I apologize for long reply. Yes it's described in documentation, this way you can send it to the server

```js
  onBlobPaste: function(blob) { // example of uploading image to server
    var formData = new FormData();
    formData.append('file', blob, 'specifyFileNameHereIfNeeded.png');
    fetch(`${host}/upload_file`, {
      method: "POST",
      body: formData,
    }).then(e => {
      console.log('server response', e);
    });
  },
```
You can also check [this source](https://github.com/akoidan/spainter/blob/master/index.html#L68)

If you want to paste it as a div:

  ```js
  const img = document.createElement("img");
  img.src = URL.createObjectURL(blob);
  ```

if you want to save it as a file from user's PC (from browser), you can save blob to a file and make an anchor tag and click on it

**Comment by rdimaunahan** [comment]
Thank you! I'll try it out.

**Comment by akoidan** [comment]
I'm closing this issue. Please check out the demo web app. [spainter.akoidan.com](https://spainter.akoidan.com) The upload feature is there. If further assistant is required feel free to reopen this issue.
